title:               elizabeth3714
url:                 https://elizabeth3714.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /portfolio/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Elizabeth Wang
  url:               elizabeth3714.github.io
  email:             elihwang@umich.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
